name: compile

on: workflow_dispatch

jobs:
  run-app:
    name: "run dart app"
    runs-on: ubuntu-latest
    steps:
      # - run: echo "AWESOME works!, triggered by ${{github.event_name}}"
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: change permissions app
        run: chmod +x ./run.sh
      - name: Hello app
      - run: ./run.sh

