name: app

run-name: my_app

on: workflow_dispatch

jobs:
  run_app:
    runs-on: ubuntu-latest
    # name: "run dart app"
    steps:
      - run: echo "AWESOME works!, triggered by ${{github.event_name}}"
     