name: app

run-name: my_app

on: workflow_dispatch

jobs:
  run_app:
    runs-on: ubuntu-latest
    # name: "run dart app"
    steps:
      - run: echo "AWESOME works!, triggered by ${{github.event_name}}"
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - run: echo "Start dart"
      - run: dart --version
      - name: current dir
        run: pwd
      - name: list dir
        run: echo "Lets get in";ls
      - run: app/run.sh
      - run: echo "Cool thanks! $pwd";
      - name: Upload Response
        uses: actions/upload-artifact@v3
        with:
          name: dart
          path: app/dart.txt