name: app

run-name: my_app

on: workflow_dispatch

jobs:
  run_app:
    name: "run dart app"
    runs-on: ubuntu-latest
    steps:
      # - run: echo "AWESOME works!, triggered by ${{github.event_name}}"
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - name: change permissions on app
      - run: echo "Start"
      - run: chmod +x ./run.sh
      - run: ./run.sh
      - run: echo "Great"